# permissions to do edit metricsservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsserver-editor-role
rules:
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers/status
  verbs:
  - get
  - patch
  - update
