# permissions to do viewer metricsservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricsserver-viewer-role
rules:
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers/status
  verbs:
  - get
