apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - addons.example.org
  resources:
  - metricsservers/status
  verbs:
  - get
  - update
  - patch
