name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

jobs:
  verify-goimports:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
          stable: true

      - run: |
          echo "::set-env name=GOPATH::${HOME}/go"

      - uses: actions/checkout@v2

      - name: verify goimports
        run: |
          files=$(go run golang.org/x/tools/cmd/goimports -format-only -l .)
          # Sadly goimports doesn't use exit codes
          if [[ -n "${files}" ]]; then
            echo "::error ::goimports should be run on these files:"
            echo "${files}"
            exit 1
          fi

  kind-e2e:
    name: Test with a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config .github/workflows/kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide